import React, { useState } from 'react';
import { Compass, Sparkles, ArrowRight, Search } from 'lucide-react';
import { DiscoverTrip } from '../types';

interface DiscoverPageProps {
  onSelectTrip: (trip: DiscoverTrip) => void;
}

const EXAMPLE_PROMPTS: Array<{ emoji: string; label: string; tag: string; promptText: string }> = [
  {
    emoji: '🇯🇵',
    label: 'Autumn Japan',
    tag: 'Hidden Gems & Food',
    promptText: "I'm planning a 7-day trip to Japan in October. I love food, hidden cafés, scenic hikes, and want to avoid crowds.",
  },
  {
    emoji: '🇮🇹',
    label: 'Slow Tuscany',
    tag: 'Slow Living & Wine',
    promptText: 'Looking for a 10-day slow travel itinerary in Tuscany, Italy, focusing on wine tasting, cooking classes, and small villages.',
  },
  {
    emoji: '🇮🇸',
    label: 'Iceland Hot Pots',
    tag: 'Dramatic Nature',
    promptText: 'I have 5 days in Iceland. I want to see the main sights but also relax in lesser-known thermal hot pots.',
  },
  {
    emoji: '🇵🇹',
    label: 'Coastal Portugal',
    tag: 'Coastal Trails',
    promptText: 'Plan a 2-week coastal road trip in Portugal for two. We love surfing, seafood, and boutique hotels.',
  },
  {
    emoji: '🇲🇦',
    label: 'Morocco Medinas',
    tag: 'Hidden Gems & Food',
    promptText: 'A 8-day journey through Morocco visiting Marrakech, Fes medina, and the Sahara desert.',
  },
  {
    emoji: '🇨🇱',
    label: 'Patagonia Trek',
    tag: 'Dramatic Nature',
    promptText: 'A 10-day hiking adventure in Patagonia focusing on the W Trek, glaciers, and wild camping.',
  },
];

export const DiscoverPage: React.FC<DiscoverPageProps> = ({ onSelectTrip }) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const categories = ['All', 'Hidden Gems & Food', 'Slow Living & Wine', 'Dramatic Nature', 'Coastal Trails'];

  const filteredPrompts = EXAMPLE_PROMPTS.filter((item) => {
    const matchesCategory = selectedCategory === 'All' || item.tag === selectedCategory;
    const matchesSearch =
      item.label.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.promptText.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const handleGenerate = (item: (typeof EXAMPLE_PROMPTS)[0]) => {
    // Build a minimal DiscoverTrip shell — real itinerary is generated by AI
    const trip: DiscoverTrip = {
      id: `prompt-${Date.now()}`,
      title: item.label,
      destination: item.label,
      duration: '',
      tag: item.tag,
      country: '',
      promptText: item.promptText,
      summary: item.promptText,
      savedCount: 0,
      curator: 'AI',
      imageUrl: '',
      highlights: [],
    };
    onSelectTrip(trip);
  };

  return (
    <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 animate-in fade-in">
      {/* Header */}
      <div className="text-center max-w-2xl mx-auto mb-10">
        <span className="text-xs font-semibold tracking-[0.2em] uppercase text-amber-900 block mb-2">
          AI-Generated Journeys
        </span>
        <h1 className="font-heading text-3xl sm:text-4xl md:text-5xl font-bold text-stone-900 tracking-tight">
          Generate a Real Itinerary
        </h1>
        <p className="mt-3 text-stone-600 text-sm sm:text-base leading-relaxed">
          Every itinerary is created live by Gemini or OpenAI — no mock data, no placeholders.
          Click any prompt to generate a fully personalised day-by-day plan.
        </p>
      </div>

      {/* Search & Category Filter Bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mb-6">
        <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto pb-1 scrollbar-none">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-4 py-2 rounded-full text-xs font-semibold tracking-wider uppercase transition-all whitespace-nowrap cursor-pointer ${
                selectedCategory === cat
                  ? 'bg-stone-900 text-white shadow-xs'
                  : 'bg-white/80 hover:bg-white text-stone-700 border border-stone-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search className="w-4 h-4 text-stone-400 absolute left-3.5 top-3" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search Kyoto, Italy..."
            className="w-full text-xs pl-9 pr-3.5 py-2.5 bg-white/90 border border-stone-200 rounded-full focus:outline-none focus:border-stone-800 text-stone-800"
          />
        </div>
      </div>

      {/* AI Notice Banner */}
      <div className="mb-8 flex items-center gap-3 p-4 rounded-2xl bg-amber-50 border border-amber-200/80">
        <Sparkles className="w-4 h-4 text-amber-700 shrink-0" />
        <p className="text-xs text-amber-900 leading-relaxed">
          <span className="font-semibold">All results are AI-generated in real time.</span>{' '}
          Click "Generate Trip" — Gemini or OpenAI will build a complete day-by-day itinerary from scratch. No saved or cached data is used.
        </p>
      </div>

      {/* Grid of Prompt Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-7">
        {filteredPrompts.map((item, idx) => (
          <article
            key={idx}
            className="group rounded-[24px] bg-[#FAF6F0] border border-stone-200/90 overflow-hidden shadow-xs hover:shadow-md transition-all duration-300 flex flex-col justify-between"
          >
            <div className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-3xl">{item.emoji}</span>
                <span className="text-[11px] font-semibold uppercase tracking-wider text-amber-800 bg-amber-50 border border-amber-200 px-2.5 py-1 rounded-full">
                  {item.tag}
                </span>
              </div>

              <h3 className="font-heading text-lg font-bold text-stone-900 leading-snug mb-3 group-hover:text-amber-950 transition-colors">
                {item.label}
              </h3>

              <p className="text-xs sm:text-sm text-stone-600 leading-relaxed line-clamp-3">
                "{item.promptText}"
              </p>
            </div>

            <div className="px-6 pb-5 pt-3 border-t border-stone-200/60 flex items-center justify-between">
              <span className="text-[11px] text-stone-400 flex items-center gap-1">
                <Sparkles className="w-3 h-3" />
                Generated by AI
              </span>

              <button
                onClick={() => handleGenerate(item)}
                className="bg-[#121212] hover:bg-stone-800 text-white text-[11px] font-semibold tracking-wider uppercase px-4 py-2 rounded-full transition-all flex items-center gap-1.5 cursor-pointer shadow-xs active:scale-95"
              >
                <span>Generate Trip</span>
                <ArrowRight className="w-3 h-3" />
              </button>
            </div>
          </article>
        ))}
      </div>

      {filteredPrompts.length === 0 && (
        <div className="text-center py-20 text-stone-400">
          <Compass className="w-10 h-10 mx-auto mb-3 opacity-30" />
          <p className="text-sm">No prompts match your search. Try a different keyword.</p>
        </div>
      )}
    </div>
  );
};
